title: Jayanth Subramanian
logo: /assets/img/Jayanth.jpg
description: Software Engineer with 4+ years experience in software development. Fascinated in the ever changing world of tech. Feeding my thirst to learn basics of machine learning.
show_downloads: false
google_analytics:
theme: jekyll-theme-minimal
